-- MySQL Script generated by MySQL Workbench
-- mer. 16 août 2023 17:32:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Onche
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Onche
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Onche` DEFAULT CHARACTER SET utf8 ;
USE `Onche` ;

-- -----------------------------------------------------
-- Table `Onche`.`onchois`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onche`.`onchois` (
  `onchois_id` INT NOT NULL AUTO_INCREMENT,
  `onchois_nom` VARCHAR(100) NOT NULL,
  `onchois_sexe` VARCHAR(30) NOT NULL DEFAULT 'None',
  `onchis_age` INT NULL,
  `onchois_QI` INT NULL,
  `onchois_qualite` FLOAT NOT NULL DEFAULT 5,
  PRIMARY KEY (`onchois_id`),
  UNIQUE INDEX `onchois_nom_UNIQUE` (`onchois_nom` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Table des onchois';


-- -----------------------------------------------------
-- Table `Onche`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onche`.`topic` (
  `id_topic` INT NOT NULL AUTO_INCREMENT,
  `topic_user` INT NOT NULL DEFAULT 1,
  `topic_nom` VARCHAR(1000) NOT NULL DEFAULT 'Erreur',
  `topic_date` TIMESTAMP(2) NOT NULL DEFAULT CURRENT_TIMESTAMP(2),
  `topic_message` INT NOT NULL DEFAULT 0,
  `topic_lien` VARCHAR(1000) NOT NULL,
  `topic_forum` TINYINT(15) NOT NULL,
  PRIMARY KEY (`id_topic`),
  INDEX `createur_idx` (`topic_user` ASC) VISIBLE,
  CONSTRAINT `createur`
    FOREIGN KEY (`topic_user`)
    REFERENCES `Onche`.`onchois` (`onchois_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `Onche`.`badges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onche`.`badges` (
  `badges_id` INT NOT NULL AUTO_INCREMENT,
  `badges_nom` VARCHAR(100) NOT NULL DEFAULT 'None',
  PRIMARY KEY (`badges_id`),
  UNIQUE INDEX `badges_nom_UNIQUE` (`badges_nom` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `Onche`.`onchois_badges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onche`.`onchois_badges` (
  `ob_id` INT NOT NULL AUTO_INCREMENT,
  `ob_userid` INT NOT NULL DEFAULT 1,
  `ob_badgeid` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ob_id`),
  INDEX `badge_idx` (`ob_badgeid` ASC) VISIBLE,
  INDEX `onchoi_idx` (`ob_userid` ASC) VISIBLE,
  CONSTRAINT `badge`
    FOREIGN KEY (`ob_badgeid`)
    REFERENCES `Onche`.`badges` (`badges_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `onchoi`
    FOREIGN KEY (`ob_userid`)
    REFERENCES `Onche`.`onchois` (`onchois_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `Onche`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onche`.`messages` (
  `id_message` INT NOT NULL AUTO_INCREMENT,
  `message_user` INT NOT NULL,
  `message_topic` INT NOT NULL,
  `message_toUser` INT NULL,
  `message_message` LONGTEXT NOT NULL,
  `message_citation` TINYINT(1) NOT NULL DEFAULT 0,
  `message_date` DATETIME(0) NOT NULL,
  PRIMARY KEY (`id_message`),
  INDEX `message_posteur_idx` (`message_user` ASC) VISIBLE,
  INDEX `message_topic_idx` (`message_topic` ASC) VISIBLE,
  INDEX `msg_toUser_idx` (`message_toUser` ASC) VISIBLE,
  CONSTRAINT `message_posteur`
    FOREIGN KEY (`message_user`)
    REFERENCES `Onche`.`onchois` (`onchois_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `message_topic`
    FOREIGN KEY (`message_topic`)
    REFERENCES `Onche`.`topic` (`id_topic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `msg_toUser`
    FOREIGN KEY (`message_toUser`)
    REFERENCES `Onche`.`onchois` (`onchois_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Table des réponses entre Onchois';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
