name: unittests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Use the Python version you need for your project
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Upgrade setuptools
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest --junitxml=reports/junit.xml
      # Adjust pytest command as needed

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-reports
        path: reports/junit.xml
